baseURL: "https://www.rubypopolsku.pl"
title: Ruby po polsku
paginate: 5
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

googleAnalytics: G-JZV7X14X6S

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: Ruby po polsku
  description: "Nauka ruby dla początkujących"
  keywords: []
  author: Tobiasz Waszak
  # author: ["Me", "You"] # multiple authors
  images: []
  DateFormat: "January 2, 2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: false
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: "<link / abs url>"
    favicon16x16: "<link / abs url>"
    favicon32x32: "<link / abs url>"
    apple_touch_icon: "<link / abs url>"
    safari_pinned_tab: "<link / abs url>"

  label:
    text: "Ruby po polsku"
    icon: /media/rubyBezTekstu.jpg
    iconHeight: 35

  # profile-mode
  profileMode:
    enabled: true # needs to be explicitly set
    title: Ruby po polsku
    subtitle: "Cześć! Nazywam się Tobiasz Waszak i wraz z Anią Kotowicz, zapraszamy do nowej serii poświęconej programowaniu w Ruby i Ruby on Rails od całkowitych podstaw. Pokażemy wam jak przyjemne, proste i szybkie jest tworzenie aplikacji przy użyciu frameworku Ruby on Rails. W tej serii skupiamy się na tworzeniu aplikacji od początku ją tworząc i przechodząc stopniowo do coraz bardziej zaawansowanych tematów. Przy okazji nie zabraknie poruszania tematów związanych z codzienną pracą jako backend developerzy gdzie dzielimy się przemyśleniami jak i naszymi potknięciami.
Jeżeli natraficie na jakieś trudności, coś jest dla was niejasne a może po prostu macie jakieś sugestie, zachęcam do kontaktu. Możecie zostawiać komentarze pod każdym filmem, albo możecie do mnie wysłać maila kontakt@rubypopolsku.pl. Postaramy się odpowiedzieć na każdy z nich."
    imageUrl: "/media/rubyBezTekstu.jpg"
    imageWidth: 120
    imageHeight: 120
    imageTitle: Ruby po polsku
    buttons:


  # home-info mode
  homeInfoParams:
    Title: "Hi there \U0001F44B"
    Content: Welcome to my blog

  socialIcons:
    - name: youtube
      url: "https://youtube.com/rubypopolsku"
    - name: github
      url: "https://github.com/rubypopolsku"
    - name: twitter
      url: "https://twitter.com/ruby_po_polsku"
    - name: instagram
      url: "https://www.instagram.com/rubypopolsku"
    - name: email
      url: "mailto:kontakt@rubypopolsku.pl"


  analytics:
    google:
      SiteVerificationTag: "XYZabc"
    bing:
      SiteVerificationTag: "XYZabc"
    yandex:
      SiteVerificationTag: "XYZabc"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

  editPost:
    URL: "https://github.com/<path_to_repo>/content"
    Text: "Suggest Changes" # edit text
    appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]
menu:
  main:
    - identifier: posts
      name: Posty
      url: /posts
      weight: 10
    - identifier: zanim_zaczniesz
      name: Zanim zaczniesz
      url: /zanim_zaczniesz
      weight: 15
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
# pygmentsUseClasses: true
# markup:
#     highlight:
#         # anchorLineNos: true
#         codeFences: true
#         guessSyntax: true
#         lineNos: true
#         style: monokai
